[package]
name = "roc_docs_types"
description = "Representations of Roc types, for use in rendering docs."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bumpalo.workspace = true
pulldown-cmark.workspace = true
const_format.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
