[package]
name = "roc_docs_render"
description = "Generates html documentation from Roc files and is used for Rocs builtins."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_docs_types = { path = "../docs_types" }
roc_highlight = { path = "../highlight" }   # TODO this brings in many deps - slim it down!
bumpalo.workspace = true
pulldown-cmark.workspace = true
const_format.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
