[package]
name = "fs"
description = "A non-allocating alternative to the small subset of Rust's std::fs that we actually need."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
