
[package]
name = "jobs"
description = "Jobs to be run either concurrently or sequentially, which can spawn other jobs."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

# [dependencies]
# arena = { path = "../arena" }
