[package]
name = "roc_scope"
description = "Managing scopes - introducing bindings etc."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
bumpalo.workspace = true
