[package]
name = "roc_can_module"
description = "Canonicalizing modules"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
roc_scope = { path = "../scope" }

bumpalo.workspace = true
