[package]
name = "arena"
description = "A growable (Vec-style) arena allocator that returns u32 indices into its memory, and can be cached to/from disk in one syscall."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
heap_alloc = { path = "../heap_alloc" }
roc_error_macros = { path = "../error_macros" }
